Vagrant.configure("2") do |config|
  config.vm.box = "envimation/ubuntu-xenial"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.hostname = "LAB8"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.provision "ansible_local" do |ans|
    ans.playbook = "playbook.yaml"
    ans.install = true
	  ans.install_mode = "pip"
    ans.pip_install_cmd  = "curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | sudo python"
  end
end
