Vagrant.configure("2") do |config|
  
  #VAGRANT BOX to use "geerlingguy/centos7"
  VAGRANT_BOX = "envimation/ubuntu-xenial"

  #VAGRANT PROVIDER CPU
  PROVIDER_CPU = 2

  #VAGRANT PROVIDER MEMORY
  PROVIDER_MEMORY = 2048

  #VAGRANT PROVIDER NAME
  PROVIDER_NAME = "LAB4"

  #VAGRAnt IP
  VAGRANT_IP = "192.168.56.4"
  
  config.vm.box = VAGRANT_BOX

  config.vm.network "private_network", ip: VAGRANT_IP

  config.vm.provider "virtualbox" do |v|
    v.name = PROVIDER_NAME
    v.cpus = PROVIDER_CPU
    v.memory = PROVIDER_MEMORY
  end
end
