Vagrant.configure("2") do |config|


  config.vm.define "lb" do |lb|
    lb.vm.box = "envimation/ubuntu-xenial"
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "10.0.0.10"

    lb.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 1024
    end
  end


  config.vm.define "web1" do |web1|
    web1.vm.box = "envimation/ubuntu-xenial"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "10.0.0.11"

    web1.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 1024
    end
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "envimation/ubuntu-xenial"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "10.0.0.12"

    web2.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 1024
    end
  end

end
