Vagrant.configure("2") do |config|

  SOURCE_FILE = "./website"
  DESTINATION_FILE = "/var/www/html"
  config.vm.box = "envimation/ubuntu-xenial"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.hostname = "LAB6"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.synced_folder SOURCE_FILE, DESTINATION_FILE
end