Vagrant.configure("2") do |config|

  #V1
  config.vm.define "lb" do |lb|
    lb.vm.box = "envimation/ubuntu-xenial"
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "10.0.0.10"

    lb.vm.provision :shell do |shell|
      shell.path = "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/lb.sh"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  #V2  
  config.vm.define "web1" do |web1|
    web1.vm.box = "envimation/ubuntu-xenial"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "10.0.0.11"

    web1.vm.provision :shell do |shell|
      shell.path = "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh"
      shell.args = "1"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  #V3
  config.vm.define "web2" do |web2|
    web2.vm.box = "envimation/ubuntu-xenial"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "10.0.0.12"

    web2.vm.provision :shell do |shell|
      shell.path = "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh"
      shell.args = "2"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

end
